version: 2

updates:

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: '09:00'
    groups:
      tfplugin:
        patterns:
          - 'github.com/hashicorp/terraform-plugin-*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: '09:00'
